version: '3.8'
networks:
  sa-network:
    name: sa-network
    driver: bridge
services:

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: "no"
    networks:
      - sa-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    networks:
      - sa-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT, DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092, DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPICS_REPLICATION_FACTOR: 1

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=sa2
    restart: "always"
    networks:
      - sa-network
    ports:
      - "3307:3306"

  instructor:
    image: instructor
    container_name: instructor
    networks:
      - sa-network
    depends_on:
      - mysql
    ports:
      - 8081:8081

  student:
    image: student
    container_name: student
    networks:
      - sa-network
    depends_on:
      - mysql

    ports:
      - 8080:8080
